<div class='footer-banner-bg'>
    <?= $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-banner-desktop-bg')
        ->toHtml() ?>
</div>
<!-- <div class="footer-banner-mobile-bg">
    <?= $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-banner-mobile-bg')
        ->toHtml() ?>
</div> -->
<div class="footer-banner-content">
    <?= $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer-banner-content')
        ->toHtml() ?>
</div>