<div class='header-top-desktop-left'>
    <?php
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('header-top-left-contact-phone')
        ->toHtml();
    ?>
</div>

<div class="header-top-desktop-center">
    <?php
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('header-top-center-links')
        ->toHtml();
    ?>
</div>


<div class="header-top-mobile-left">
    <img src="<?php echo $this->getViewFileUrl('images/ic_place_black_24px.png'); ?>" width="12" height="16" alt="Phone Number" />
    <?= $block->getLayout()
        ->createBlock("Magento\Cms\Block\Block")
        ->setBlockId("header-top-left-mobile-address")
        ->toHtml()
    ?>
</div>
<div class="header-top-mobile-right">
    <img src="<?php echo $this->getViewFileUrl('images/ic_phone_black_24px.png'); ?>" alt="Address" width="14" height="14" alt="Address" />
    <?= $block->getLayout()
        ->createBlock("Magento\Cms\Block\Block")
        ->setBlockId("header-top-mobile-phone-contact")
        ->toHtml()
    ?>
</div>