<div class="banner">
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_top_img_2')->toHtml();?>
    <div class="banner_content">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_top_text_2')->toHtml();?>
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_top_button')->toHtml();?>
    </div>
</div>