<!-- <div class="section-demo-new-seller">
    <div class="title">
        <?php
            echo $block->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('title-new-arrivals')
                    ->toHtml();
        ?>
    </div>

    <div class="content">
        <?php
            echo $block->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('demo-best-seller')
                    ->toHtml();
        ?>
    </div>
</div> -->