<div class="our-blog">
    <?= 
    $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ourblog_head')->toHtml();
    ?>
    <div class="row">
        <?php for ($i=1; $i <=6 ; $i++):?>
            <div class="furniture-blog">
                <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId("ourblog_item_$i")->toHtml();?>
            </div>
        <?php endfor?>
    </div>
    
</div>