<div class="section-new-seller">
    <?php
    echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('new-sellers')
            ->toHtml();
    ?>
</div>

<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".product-items").slick({
                slidesToShow: 4,
                slidesToScroll: 4,
                dots: false,
                infinite: true,
                speed: 300,
                responsive: [
                    {
                        breakpoint: 1024,
                        settings: {
                            rows: 2,
                            slidesToShow: 2,
                            slidesToScroll: 2,
                            dots: false,
                            arrows: false,
                            infinite: true
                        }
                    },
                    {
                        breakpoint: 768,
                        settings: {
                            rows: 2,
                            slidesToShow: 2,
                            slidesToScroll: 2,
                            dots: false,
                            arrows: false,
                            infinite: true
                        }
                    },
                    {
                        breakpoint: 640,
                        settings: {
                            rows: 2,
                            slidesToShow: 2,
                            slidesToScroll: 2,
                            dots: false,
                            arrows: false,
                            infinite: true
                        }
                    }
                ]
            });
        });
    });
</script>

